In [2]:
import math

import numpy as np
import pandas as pd
from sqlalchemy import column, Null

from extract import load_dataframe

In [3]:
dados = load_dataframe()
df = dados['circuits']
df.head()

,circuit_id,circuit_name,locality,country,lat,lng,url
0,adelaide,Adelaide Street Circuit,Adelaide,Australia,-34.9272,138.61700,https://en.wikipedia.org/wiki/Adelaide_Street_...
1,ain-diab,Ain Diab,Casablanca,Morocco,33.5786,-7.68750,https://en.wikipedia.org/wiki/Ain-Diab_Circuit
2,aintree,Aintree,Liverpool,UK,53.4769,-2.94056,https://en.wikipedia.org/wiki/Aintree_Motor_Ra...
3,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.96800,https://en.wikipedia.org/wiki/Albert_Park_Circuit
4,americas,Circuit of the Americas,Austin,USA,30.1328,-97.64110,https://en.wikipedia.org/wiki/Circuit_of_the_A...

In [74]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   circuit_id    78 non-null     str
 1   circuit_name  78 non-null     str
 2   locality      78 non-null     str
 3   country       78 non-null     str
 4   lat           78 non-null     float64
 5   lng           78 non-null     float64
 6   url           78 non-null     str
dtypes: float64(2), str(5)
memory usage: 4.4 KB

In [75]:
df.duplicated().sum()

np.int64(0)

In [112]:
df.columns = ['circuito_id', 'nome_circuito', 'localidade', 'pais', 'latitude', 'longitude', 'url']
df

,circuito_id,nome_circuito,localidade,pais,latitude,longitude,url
0,adelaide,Adelaide Street Circuit,Adelaide,Australia,-34.9272,138.61700,https://en.wikipedia.org/wiki/Adelaide_Street_...
1,ain-diab,Ain Diab,Casablanca,Morocco,33.5786,-7.68750,https://en.wikipedia.org/wiki/Ain-Diab_Circuit
2,aintree,Aintree,Liverpool,UK,53.4769,-2.94056,https://en.wikipedia.org/wiki/Aintree_Motor_Ra...
3,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.96800,https://en.wikipedia.org/wiki/Albert_Park_Circuit
4,americas,Circuit of the Americas,Austin,USA,30.1328,-97.64110,https://en.wikipedia.org/wiki/Circuit_of_the_A...
...,...,...,...,...,...,...,...
73,yas_marina,Yas Marina Circuit,Abu Dhabi,UAE,24.4672,54.60310,https://en.wikipedia.org/wiki/Yas_Marina_Circuit
74,yeongam,Korean International Circuit,Yeongam County,Korea,34.7333,126.41700,https://en.wikipedia.org/wiki/Korea_Internatio...
75,zandvoort,Circuit Park Zandvoort,Zandvoort,Netherlands,52.3888,4.54092,https://en.wikipedia.org/wiki/Circuit_Zandvoort
76,zeltweg,Zeltweg,Styria,Austria,47.2039,14.74780,https://en.wikipedia.org/wiki/Zeltweg_Air_Base
77,zolder,Zolder,Heusden-Zolder,Belgium,50.9894,5.25694,https://en.wikipedia.org/wiki/Circuit_Zolder

In [78]:
df2 = dados['constructor_standings']
df2.head()

   edição  posição  pontos  vitórias id_construtora construtora
0    1958      1.0    48.0         6        vanwall     Vanwall
1    1958      2.0    40.0         2        ferrari     Ferrari
2    1958      3.0    31.0         2         cooper      Cooper
3    1958      4.0    18.0         0            brm         BRM
4    1958      5.0     6.0         0       maserati    Maserati

In [20]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 924 entries, 0 to 923
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   season          924 non-null    int64
 1   position        712 non-null    float64
 2   points          924 non-null    float64
 3   wins            924 non-null    int64
 4   constructor_id  924 non-null    str
 5   constructor     924 non-null    str
dtypes: float64(2), int64(2), str(2)
memory usage: 43.4 KB

In [76]:
df2.duplicated().sum()

np.int64(0)

In [23]:
df2.isnull().sum()

season              0
position          212
points              0
wins                0
constructor_id      0
constructor         0
dtype: int64

In [66]:
df2.fillna({'position': 6.0}, inplace=True).isna().sum()

season            0
position          0
points            0
wins              0
constructor_id    0
constructor       0
dtype: int64

In [77]:
df2.columns = ['edicao', 'posicao_final', 'pontos', 'vitórias', 'id_construtora', 'construtora']

In [70]:
df3 = dados[('constructors')]
df3.head()

,constructor_id,name,nationality,url
0,adams,Adams,American,https://en.wikipedia.org/wiki/Adams_(constructor)
1,afm,AFM,German,https://en.wikipedia.org/wiki/Alex_von_Falkenh...
2,ags,AGS,French,https://en.wikipedia.org/wiki/Automobiles_Gonf...
3,alfa,Alfa Romeo,Swiss,https://en.wikipedia.org/wiki/Alfa_Romeo_in_Fo...
4,alphatauri,AlphaTauri,Italian,https://en.wikipedia.org/wiki/Scuderia_AlphaTauri

In [79]:
df3.columns = ['id_construtora', 'nome','nacionalidade', 'url']

In [80]:
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_construtora  214 non-null    str
 1   nome            214 non-null    str
 2   nacionalidade   214 non-null    str
 3   url             214 non-null    str
dtypes: str(4)
memory usage: 6.8 KB

In [73]:
df3.isnull().sum()

constructor_id    0
name              0
nationality       0
url               0
dtype: int64

In [83]:
df3.duplicated().sum()

np.int64(0)

In [85]:
df4 = dados['driver_standings']
df4.head()

   season  position  points  wins driver_id  constructor
0    1950       1.0    30.0     3    farina   Alfa Romeo
1    1950       2.0    27.0     3    fangio   Alfa Romeo
2    1950       3.0    24.0     0   fagioli   Alfa Romeo
3    1950       4.0    13.0     0    rosier  Talbot-Lago
4    1950       5.0    11.0     0    ascari      Ferrari

In [86]:
df4.columns = ['edição', 'posição', 'pontos','vitórias', 'id_corredor', 'construtora']
df4.info()

<class 'pandas.DataFrame'>
RangeIndex: 3128 entries, 0 to 3127
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   edição       3128 non-null   int64
 1   posição      1664 non-null   float64
 2   pontos       3128 non-null   float64
 3   vitórias     3128 non-null   int64
 4   id_corredor  3128 non-null   str
 5   construtora  3128 non-null   str
dtypes: float64(2), int64(2), str(2)
memory usage: 146.8 KB

In [88]:
df4.isnull().sum()

edição            0
posição        1464
pontos            0
vitórias          0
id_corredor       0
construtora       0
dtype: int64

In [90]:
df4['posição'].unique()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., nan, 23., 24., 25.,
       26., 27., 28., 29.])

In [92]:
df4.describe()

            edição      posição       pontos     vitórias
count  3128.000000  1664.000000  3128.000000  3128.000000
mean   1978.100064    11.515024    18.050086     0.369246
std      22.037585     6.592221    50.905204     1.338290
min    1950.000000     1.000000     0.000000     0.000000
25%    1958.000000     6.000000     0.000000     0.000000
50%    1974.000000    11.000000     0.000000     0.000000
75%    1994.000000    17.000000    11.000000     0.000000
max    2026.000000    29.000000   575.000000    19.000000

In [93]:
df4.fillna({'posição': df4['posição'].mean()}, inplace = True)

      edição  posição  pontos  vitórias id_corredor       construtora
0       1950      1.0    30.0         3      farina        Alfa Romeo
1       1950      2.0    27.0         3      fangio        Alfa Romeo
2       1950      3.0    24.0         0     fagioli        Alfa Romeo
3       1950      4.0    13.0         0      rosier       Talbot-Lago
4       1950      5.0    11.0         0      ascari           Ferrari
...      ...      ...     ...       ...         ...               ...
3123    2026     18.0     0.0         0       albon          Williams
3124    2026     19.0     0.0         0      bottas  Cadillac F1 Team
3125    2026     20.0     0.0         0       perez  Cadillac F1 Team
3126    2026     21.0     0.0         0      alonso      Aston Martin
3127    2026     22.0     0.0         0      stroll      Aston Martin

[3128 rows x 6 columns]

In [95]:
df4.isnull().sum()

edição         0
posição        0
pontos         0
vitórias       0
id_corredor    0
construtora    0
dtype: int64

In [97]:
df4.duplicated().sum()

np.int64(0)

In [114]:
df5 = dados['drivers']
df5.head()

,driver_id,given_name,family_name,dob,nationality,number,code,url
0,abate,Carlo,Abate,1932-07-10,Italian,NaN,NaN,http://en.wikipedia.org/wiki/Carlo_Mario_Abate
1,abecassis,George,Abecassis,1913-03-21,British,NaN,NaN,http://en.wikipedia.org/wiki/George_Abecassis
2,acheson,Kenny,Acheson,1957-11-27,British,NaN,NaN,http://en.wikipedia.org/wiki/Kenny_Acheson
3,adams,Philippe,Adams,1969-11-19,Belgian,NaN,NaN,http://en.wikipedia.org/wiki/Philippe_Adams
4,ader,Walt,Ader,1913-12-15,American,NaN,NaN,http://en.wikipedia.org/wiki/Walt_Ader

In [115]:
df5.columns = ['id_corredor', 'nome_informado', 'nome_de_familia','data_de_nascimento','nacionalidade','numero','codigo','url']

In [116]:
df5.info()

<class 'pandas.DataFrame'>
RangeIndex: 879 entries, 0 to 878
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_corredor         879 non-null    str
 1   nome_informado      879 non-null    str
 2   nome_de_familia     879 non-null    str
 3   data_de_nascimento  865 non-null    str
 4   nacionalidade       865 non-null    str
 5   numero              63 non-null     float64
 6   codigo              107 non-null    str
 7   url                 865 non-null    str
dtypes: float64(1), str(7)
memory usage: 55.1 KB

In [104]:
df5.describe()

          number
count  63.000000
mean   32.222222
std    29.367221
min     1.000000
25%     9.500000
50%    22.000000
75%    44.500000
max    99.000000

In [105]:
df5.isnull().sum()

driver_id        0
given_name       0
family_name      0
dob             14
nationality     14
number         816
code           772
url             14
dtype: int64

In [107]:
df5.duplicated().sum()

np.int64(0)

In [117]:
df5['data_de_nascimento'] = pd.to_datetime(df5['data_de_nascimento'], errors='coerce')

In [138]:
df6 = dados['qualifying']
df6.head()

,edição,etapa,id_corredor,id_construtora,posição,Q1,Q2,Q3
0,1994,1,senna,williams,1,1:15.962,NaN,NaN
1,1994,1,michael_schumacher,benetton,2,1:16.290,NaN,NaN
2,1994,1,alesi,ferrari,3,1:17.385,NaN,NaN
3,1994,1,damon_hill,williams,4,1:17.554,NaN,NaN
4,1994,1,frentzen,sauber,5,1:17.806,NaN,NaN

In [139]:
df6.columns = ['edição', 'etapa', 'id_corredor', 'id_construtora', 'posição', 'Q1', 'Q2', 'Q3']
df6.info()

<class 'pandas.DataFrame'>
RangeIndex: 11036 entries, 0 to 11035
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   edição          11036 non-null  int32
 1   etapa           11036 non-null  int64
 2   id_corredor     11036 non-null  str
 3   id_construtora  11036 non-null  str
 4   posição         11036 non-null  int64
 5   Q1              10873 non-null  str
 6   Q2              6248 non-null   str
 7   Q3              3895 non-null   str
dtypes: int32(1), int64(2), str(5)
memory usage: 646.8 KB

In [135]:
df6['edição'] = pd.to_datetime(df6['edição'], errors='coerce')
df6['edição'] = df6['edição'].dt.year

In [141]:
df6.isnull().sum()

edição               0
etapa                0
id_corredor          0
id_construtora       0
posição              0
Q1                 163
Q2                4788
Q3                7141
dtype: int64

In [143]:
df6.duplicated().sum()

np.int64(0)

In [146]:
df7 = dados['races']
df7.head()

,season,round,race_name,circuit_id,date,time,url
0,1950,1,British Grand Prix,silverstone,1950-05-13,NaN,https://en.wikipedia.org/wiki/1950_British_Gra...
1,1950,2,Monaco Grand Prix,monaco,1950-05-21,NaN,https://en.wikipedia.org/wiki/1950_Monaco_Gran...
2,1950,3,Indianapolis 500,indianapolis,1950-05-30,NaN,https://en.wikipedia.org/wiki/1950_Indianapoli...
3,1950,4,Swiss Grand Prix,bremgarten,1950-06-04,NaN,https://en.wikipedia.org/wiki/1950_Swiss_Grand...
4,1950,5,Belgian Grand Prix,spa,1950-06-18,NaN,https://en.wikipedia.org/wiki/1950_Belgian_Gra...

In [147]:
df7.columns = ['edicao', 'etapa', 'nome_da_corrida','id_do_circuito','data_da_corrida','horario', 'url']
df7.info()

<class 'pandas.DataFrame'>
RangeIndex: 1171 entries, 0 to 1170
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   edicao           1171 non-null   int64
 1   etapa            1171 non-null   int64
 2   nome_da_corrida  1171 non-null   str
 3   id_do_circuito   1171 non-null   str
 4   data_da_corrida  1171 non-null   str
 5   horario          440 non-null    str
 6   url              1171 non-null   str
dtypes: int64(2), str(5)
memory usage: 64.2 KB

In [148]:
df7['data_da_corrida'] = pd.to_datetime(df7['data_da_corrida'], errors='coerce')
df7.head()

,edicao,etapa,nome_da_corrida,id_do_circuito,data_da_corrida,horario,url
0,1950,1,British Grand Prix,silverstone,1950-05-13,NaN,https://en.wikipedia.org/wiki/1950_British_Gra...
1,1950,2,Monaco Grand Prix,monaco,1950-05-21,NaN,https://en.wikipedia.org/wiki/1950_Monaco_Gran...
2,1950,3,Indianapolis 500,indianapolis,1950-05-30,NaN,https://en.wikipedia.org/wiki/1950_Indianapoli...
3,1950,4,Swiss Grand Prix,bremgarten,1950-06-04,NaN,https://en.wikipedia.org/wiki/1950_Swiss_Grand...
4,1950,5,Belgian Grand Prix,spa,1950-06-18,NaN,https://en.wikipedia.org/wiki/1950_Belgian_Gra...

In [149]:
df7.isnull().sum()

edicao               0
etapa                0
nome_da_corrida      0
id_do_circuito       0
data_da_corrida      0
horario            731
url                  0
dtype: int64

In [150]:
df7.duplicated().sum()

np.int64(0)

In [4]:
df8 = dados['results']
df8.head()

,season,round,race_name,driver_id,driver_name,constructor_id,constructor,grid,position,points,laps,status,time,fastest_lap,fastest_lap_rank
0,1950,1,British Grand Prix,farina,Nino Farina,alfa,Alfa Romeo,1,1,9.0,70,Finished,2:13:23.600,NaN,NaN
1,1950,1,British Grand Prix,fagioli,Luigi Fagioli,alfa,Alfa Romeo,2,2,6.0,70,Finished,+2.600,NaN,NaN
2,1950,1,British Grand Prix,reg_parnell,Reg Parnell,alfa,Alfa Romeo,4,3,4.0,70,Finished,+52.000,NaN,NaN
3,1950,1,British Grand Prix,cabantous,Yves Cabantous,lago,Talbot-Lago,6,4,3.0,68,+2 Laps,NaN,NaN,NaN
4,1950,1,British Grand Prix,rosier,Louis Rosier,lago,Talbot-Lago,9,5,2.0,68,+2 Laps,NaN,NaN,NaN

In [7]:
df8.columns = ['edicao', 'etapa', 'nome_da_corrida', 'id_corredor', 'nome_do_corredor', 'id_construtora', 'construtora', 'posicao_de_largada', 'posicao_no_final', 'pontos', 'voltas', 'status', 'tempo', 'volta_mais_rapida', 'classificacao_da_volta_mais_rapida']
df8.info()

<class 'pandas.DataFrame'>
RangeIndex: 25939 entries, 0 to 25938
Data columns (total 15 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   edicao                              25939 non-null  int64
 1   etapa                               25939 non-null  int64
 2   nome_da_corrida                     25939 non-null  str
 3   id_corredor                         25939 non-null  str
 4   nome_do_corredor                    25939 non-null  str
 5   id_construtora                      25939 non-null  str
 6   construtora                         25939 non-null  str
 7   posicao_de_largada                  25939 non-null  int64
 8   posicao_no_final                    25939 non-null  int64
 9   pontos                              25939 non-null  float64
 10  voltas                              25939 non-null  int64
 11  status                              25939 non-null  str
 12  tempo                               8354 non-null   str
 13  volta_mais_rapida                   8785 non-null   str
 14  classificacao_da_volta_mais_rapida  8785 non-null   float64
dtypes: float64(2), int64(5), str(8)
memory usage: 3.0 MB

In [9]:
df8.isnull().sum()

edicao                                    0
etapa                                     0
nome_da_corrida                           0
id_corredor                               0
nome_do_corredor                          0
id_construtora                            0
construtora                               0
posicao_de_largada                        0
posicao_no_final                          0
pontos                                    0
voltas                                    0
status                                    0
tempo                                 17585
volta_mais_rapida                     17154
classificacao_da_volta_mais_rapida    17154
dtype: int64

In [10]:
df8.duplicated().sum()

np.int64(0)